# name of the application
spring.application.name=financetracker-api

# tell Spring Boot to use SQLite instead of H2
spring.datasource.url=jdbc:sqlite:data/financetracker.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# tell Hibernate to use SQLite dialect
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# show SQL queries in the console so we can see what's happening
spring.jpta.show-sql=true