# application name
spring.application.name=financetracker-api

# database connection
# Railway production: DATABASE_URL is set automatically by Railway when PostgreSQL is added
# Docker local: DATABASE_URL is set in docker-compose.yml as jdbc:postgresql://db:5432/financetracker
# both environments use the same variable name so the same code works in both places
spring.datasource.url=${DATABASE_URL}

# tells Spring Boot which driver to use to talk to PostgreSQL
# a driver is like a translator between Java and the database
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate dialect ? tells Hibernate to use PostgreSQL's version of SQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# update = create tables if they don't exist, never delete existing data
spring.jpa.hibernate.ddl-auto=update

# show SQL queries in console so we can see what is happening
spring.jpa.show-sql=true