# application name
spring.application.name=financetracker-api

# database connection
# Railway automatically creates a DATABASE_URL variable when PostgreSQL is added
# it looks like: postgresql://user:password@host:5432/railway
# Spring Boot reads it directly from Railway's environment
spring.datasource.url=${DATABASE_URL}

# tells Spring Boot which driver to use to talk to PostgreSQL
# a driver is like a translator between Java and the database
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate dialect ? tells Hibernate to use PostgreSQL's version of SQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# update = create tables if they don't exist, never delete existing data
spring.jpa.hibernate.ddl-auto=update

# show SQL queries in console so we can see what is happening
spring.jpa.show-sql=true